### ISSUE TITLE
[Bug]: Videos Stuck On "Buffering" Or "Preparing..."

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [vzhd1701/gridplayer#276]
### GridPlayer version

0.5.4

### What OS are you using?

Linux

### OS Version / Linux distribution

CachyOS

### What distribution channel are you using? [LINUX ONLY]

None

### Bug description

Seeing as all pre-built versions fail to even launch, I finally managed to build gridplayer using poetry with `uv venv -p 3.10`. But when running gridplayer, I only get audio playback, no matter what video decoding option or how many videos-per-process are chosen. And even then, the audio keeps playing after I've closed the file or the gridplayer window itself. There doesn't seem to be any relevant error/warning outputs from the Konsole. Just the annyoing Qt message: `| QT | warning | Wayland does not support QWindow::requestActivate()`

### Log excerpt

```shell

```

**Comment by avczar** [comment]
@vzhd1701 
Thank you, but I want use Flatpak or AppImage only (and no any of both works), no direct install. So i can't test that, sorry.

**Comment by vzhd1701** [comment]
Fixed in v0.5.5

**Comment by avczar** [comment]
New test with fresh install of v0.5.5 with AppImage and Flatpak: nothing has changed; it still doesn't work.

**Comment by vzhd1701** [comment]
Go to `Settings -> Miscellaneous -> Advanced` and turn on the `Opaque overlay` option
